name: MultiWorld
main: pl.moresteck.multiworld.MultiWorld
version: 2.0.3
description: Provides multi-world support for Bukkit.
author: Moresteck
website: https://betacraft.ovh/
load: postworld
softdepend: [Permissions, PermissionsEx]

commands:
    mw:
        usage: /mw
        description: MultiWorld main command