name: MultiWorld
main: bc.pl.daamazingshit.MultiWorld
version: 0.3
author: DaAmazingShit
description: Allows to have more than one world on your server
commands:
    mw:
        usage: /<command>
        description: Plugin management
