name: MultiWorld
version: "1.0-beta" // NOT recommended now, unfinished.
main: pl.DaAmazingShit.MultiWorld.MultiWorldMain
commands:
    multiworld:
        usage: /multiworld
        aliases: [mw]
        description : |
            MultiWorld help