name: MultiWorld
main: pl.moresteck.multiworld.MultiWorld
version: 2.0-Pre1
description: Provides multi-world support for Bukkit.
author: Moresteck
website: https://betacraft.ovh/
load: postworld
softdepend: [BukkitVersion]

commands:
    mw:
        usage: /mw
        description: MultiWorld main command
    testentity:
        usage: /<command>
        description: Shows current entities in world (testing purpose)