name: MultiWorld
version: 1.0.1
main: pl.amazingshit.mw.MultiWorld
author: DaAmazingShit

commands:
    multiworld:
        usage: /<command>
        aliases: [mw]
        description: |
            Shows MultiWorld help.
    worldsettings:
        usage: /<command>
        aliases: [ws]
        description: |
            Manages world settings.
    worldlist:
        usage: /<command>
        aliases: [wl]
        description: |
            Shows loaded world list.